//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsl.Info.Cadastrais.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsl.Info.Cadastrais.Domain.Resources.MensagensInfo", typeof(MensagensInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPS!!! Já existe um cliente cadastrado com o CPF informado..
        /// </summary>
        public static string Cliente_CpfExistente {
            get {
                return ResourceManager.GetString("Cliente_CpfExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar cliente com o CPF informado!.
        /// </summary>
        public static string Cliente_ErroDeletar {
            get {
                return ResourceManager.GetString("Cliente_ErroDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado cliente com o CPF informado!.
        /// </summary>
        public static string Cliente_NaoEncontrado {
            get {
                return ResourceManager.GetString("Cliente_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um depósito cadastrado com o código informado..
        /// </summary>
        public static string Deposito_CodigoExiste {
            get {
                return ResourceManager.GetString("Deposito_CodigoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar depósito com o código informado!.
        /// </summary>
        public static string Deposito_ErroDeletar {
            get {
                return ResourceManager.GetString("Deposito_ErroDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado um depósito com o código informado!.
        /// </summary>
        public static string Deposito_NaoEncontrado {
            get {
                return ResourceManager.GetString("Deposito_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um fornecedor cadastrado com o CNPJ informado..
        /// </summary>
        public static string Fornecedor_CpnjExiste {
            get {
                return ResourceManager.GetString("Fornecedor_CpnjExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar fornecedor com o CNPJ informado!.
        /// </summary>
        public static string Fornecedor_ErroDeletar {
            get {
                return ResourceManager.GetString("Fornecedor_ErroDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado fornecedor com o CNPJ informado..
        /// </summary>
        public static string Fornecedor_NaoEncontrado {
            get {
                return ResourceManager.GetString("Fornecedor_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe uma mercadoria cadastrada com o código informado..
        /// </summary>
        public static string Mercadoria_CodigoExiste {
            get {
                return ResourceManager.GetString("Mercadoria_CodigoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar mercadoria com o código informado!.
        /// </summary>
        public static string Mercadoria_ErroDeletar {
            get {
                return ResourceManager.GetString("Mercadoria_ErroDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada uma mercadoria com o código informado!.
        /// </summary>
        public static string Mercadoria_NaoEncontrada {
            get {
                return ResourceManager.GetString("Mercadoria_NaoEncontrada", resourceCulture);
            }
        }
    }
}
